version: '3.7'

services:
  web:
    image: httpd:2.4
    ports:
      - '8000:80'
    working_dir: /usr/local/apache2/htdocs
    depends_on:
      - nodejs
    volumes:
      - ./samples/html:/usr/local/apache2/htdocs

  nodejs:
    image: node:16
    user: node
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: bash -c "npm install && npm run build-samples"
